data_directory: "{__dir__}/../data"
random_state: &random_state 1234

dataset:
  directory: baselines
  network_split: 4567
  pca_n_components: 100
  missings_threshold: 0.5
  zeros_threshold: 0.9
  neg_to_pos_ratio: 1
  clean_arrays: True

models:
  # Organisms:  "all", [], or any subset of [5664, 5691, 5833]
  model_other_organisms: all      # organisms used in overall dataset; should be fixed
  retain_train_organisms: all     # organisms used in training splits; vary for comparison

  # Global model settings
  constants:
    verbosity: 100
    early_stopping_rounds: 50     # disabled when getting test results
    random_state: *random_state

  # Specific model settings and hypers
  lr:
    transform_X: true
    max_iter: 200
    C: 100

  xgb:
    transform_X: false
    num_boost_round: 433
    lambda: 10
    alpha: 0
    eta: 0.1
    max_depth: 10

  lgb:
    transform_X: false
    num_boost_round: 392
    lambda_l1: 0.1
    lambda_l2: 10
    learning_rate: 0.5
    max_depth: 10

  mlp:
    transform_X: true
    max_iter: 500
    hidden_dim: 40
    hidden_layers: 3
    lr: 0.001
    weight_decay: 0.01
    dropout_p: 0
    batch_size: null
